export const INSTALLMENT_LIST_REQUEST = 'INSTALLMENT_LIST_REQUEST'
export const INSTALLMENT_LIST_SUCCESS = 'INSTALLMENT_LIST_SUCCESS'
export const INSTALLMENT_LIST_FAIL = 'INSTALLMENT_LIST_FAIL'

export const INSTALLMENT_CREATE_REQUEST = 'INSTALLMENT_CREATE_REQUEST'
export const INSTALLMENT_CREATE_SUCCESS = 'INSTALLMENT_CREATE_SUCCESS'
export const INSTALLMENT_CREATE_FAIL = 'INSTALLMENT_CREATE_FAIL'
export const INSTALLMENT_CREATE_RESET = 'INSTALLMENT_CREATE_RESET'

export const CREDIT_LIST_REQUEST = 'CREDIT_LIST_REQUEST'
export const CREDIT_LIST_SUCCESS = 'CREDIT_LIST_SUCCESS'
export const CREDIT_LIST_FAIL = 'CREDIT_LIST_FAIL'

export const INSTALLMENT_DELETE_REQUEST = 'INSTALLMENT_DELETE_REQUEST'
export const INSTALLMENT_DELETE_SUCCESS = 'INSTALLMENT_DELETE_SUCCESS'
export const INSTALLMENT_DELETE_FAIL = 'INSTALLMENT_DELETE_FAIL'

export const INSTALLMENT_UPDATE_REQUEST = 'INSTALLMENT_UPDATE_REQUEST'
export const INSTALLMENT_UPDATE_SUCCESS = 'INSTALLMENT_UPDATE_SUCCESS'
export const INSTALLMENT_UPDATE_FAIL = 'INSTALLMENT_UPDATE_FAIL'
export const INSTALLMENT_UPDATE_RESET = 'INSTALLMENT_UPDATE_RESET'