export const SALE_LIST_REQUEST = 'SALE_LIST_REQUEST'
export const SALE_LIST_SUCCESS = 'SALE_LIST_SUCCESS'
export const SALE_LIST_FAIL = 'SALE_LIST_FAIL'

export const SALE_CREATE_REQUEST = 'SALE_CREATE_REQUEST'
export const SALE_CREATE_SUCCESS = 'SALE_CREATE_SUCCESS'
export const SALE_CREATE_FAIL = 'SALE_CREATE_FAIL'
export const SALE_CREATE_RESET = 'SALE_CREATE_RESET'

export const SALES_TREND_REQUEST = 'SALES_TREND_REQUEST'
export const SALES_TREND_SUCCESS = 'SALES_TREND_SUCCESS'
export const SALES_TREND_FAIL = 'SALES_TREND_FAIL'

export const SALES_PER_PRODUCT_REQUEST = 'SALES_PER_PRODUCT_REQUEST'
export const SALES_PER_PRODUCT_SUCCESS = 'SALES_PER_PRODUCT_SUCCESS'
export const SALES_PER_PRODUCT_FAIL = 'SALES_PER_PRODUCT_FAIL'

export const PRODUCT_SALES_TREND_REQUEST = 'PRODUCT_SALES_TREND_REQUEST'
export const PRODUCT_SALES_TREND_SUCCESS = 'PRODUCT_SALES_TREND_SUCCESS'
export const PRODUCT_SALES_TREND_FAIL = 'PRODUCT_SALES_TREND_FAIL'

export const SALE_DELETE_REQUEST = 'SALE_DELETE_REQUEST'
export const SALE_DELETE_SUCCESS = 'SALE_DELETE_SUCCESS'
export const SALE_DELETE_FAIL = 'SALE_DELETE_FAIL'

export const SALE_UPDATE_REQUEST = 'SALE_UPDATE_REQUEST'
export const SALE_UPDATE_SUCCESS = 'SALE_UPDATE_SUCCESS'
export const SALE_UPDATE_FAIL = 'SALE_UPDATE_FAIL'
export const SALE_UPDATE_RESET = 'SALE_UPDATE_RESET'