export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'


export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'


export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST'
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS'
export const MEMBER_CREATE_FAIL = 'MEMBER_CREATE_FAIL'
export const MEMBER_CREATE_RESET = 'MEMBER_CREATE_RESET'

export const MEMBER_DETAILS_REQUEST = 'MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCCESS = 'MEMBER_DETAILS_SUCCESS'
export const MEMBER_DETAILS_FAIL = 'MEMBER_DETAILS_FAIL'
export const MEMBER_DETAILS_RESET = 'MEMBER_DETAILS_RESET'

export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL'
export const MEMBER_LIST_RESET = 'MEMBER_LIST_RESET'


export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST'
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS'
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL'


export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST'
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS'
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL'
export const MEMBER_UPDATE_RESET = 'MEMBER_UPDATE_RESET'
