export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'

export const VENDOR_CREATE_REQUEST = 'VENDOR_CREATE_REQUEST'
export const VENDOR_CREATE_SUCCESS = 'VENDOR_CREATE_SUCCESS'
export const VENDOR_CREATE_FAIL = 'VENDOR_CREATE_FAIL'
export const VENDOR_CREATE_RESET = 'VENDOR_CREATE_RESET'